routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@index');

Route::prefix('/{country}')->group(function () {
    Route::get('/', 'HomeController@country')->name('getCountry');

    Route::get('/rankings/{city?}', 'RankingController@index')->name('getRankings');
    Route::get('/boxplot/{city?}', 'BoxplotController@index')->name('getBoxplot');
    Route::get('/boxplot-data/{city?}', 'BoxplotController@boxplot')->name('getBoxplotApi');
    Route::get('/weekcalendar/{city?}', 'CalendarHeatmapController@index')->name('getCalendarHeatmap');

    Route::get('/{city}', 'HomeController@city')->name('getCity');
});

app/Models/Dish.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;

class Dish extends Model
{
    protected $guarded = [];

    public function restaurant()
    {
        return $this->belongsTo(Restaurant::class);
    }

    public function getReadablePriceAttribute()
    {
        return '$' . $this->price;
    }

    public function scopeFromRestaurants($query, Collection $restaurants)
    {
        return $query->whereIn('restaurant_id', $restaurants->pluck('id')->toArray());
    }

    public function scopeFromArea($query, Area $area)
    {
        $restaurants = Restaurant::fromArea($area)->pluck('id')->toArray();
        return $query->whereIn('restaurant_id', $restaurants);
    }

    public function scopeFromCity($query, City $city)
    {
        $restaurants = Restaurant::fromCity($city)->pluck('id')->toArray();
        return $query->whereIn('restaurant_id', $restaurants);
    }

    public function scopeFromCountry($query, Country $country)
    {
        $restaurants = Restaurant::fromCountry($country)->pluck('id')->toArray();
        return $query->whereIn('restaurant_id', $restaurants);
    }
}

resources/views/site/partials/_chivito-index.blade.php
{{-- <table class="table">
  <thead>
    <tr>
      <th><abbr title="Position">Pos</abbr></th>
      <th>Team</th>
      <th><abbr title="Played">Pld</abbr></th>
      <th><abbr title="Won">W</abbr></th>
      <th><abbr title="Drawn">D</abbr></th>
      <th><abbr title="Lost">L</abbr></th>
      <th><abbr title="Goals for">GF</abbr></th>
      <th><abbr title="Goals against">GA</abbr></th>
      <th><abbr title="Goal difference">GD</abbr></th>
      <th><abbr title="Points">Pts</abbr></th>
      <th>Qualification or relegation</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th><abbr title="Position">Pos</abbr></th>
      <th>Team</th>
      <th><abbr title="Played">Pld</abbr></th>
      <th><abbr title="Won">W</abbr></th>
      <th><abbr title="Drawn">D</abbr></th>
      <th><abbr title="Lost">L</abbr></th>
      <th><abbr title="Goals for">GF</abbr></th>
      <th><abbr title="Goals against">GA</abbr></th>
      <th><abbr title="Goal difference">GD</abbr></th>
      <th><abbr title="Points">Pts</abbr></th>
      <th>Qualification or relegation</th>
    </tr>
  </tfoot>
  <tbody>
    <tr>
      <th>1</th>
      <td><a href="https://en.wikipedia.org/wiki/Leicester_City_F.C." title="Leicester City F.C.">Leicester City</a> <strong>(C)</strong>
      </td>
      <td>38</td>
      <td>23</td>
      <td>12</td>
      <td>3</td>
      <td>68</td>
      <td>36</td>
      <td>+32</td>
      <td>81</td>
      <td>Qualification for the <a href="https://en.wikipedia.org/wiki/2016%E2%80%9317_UEFA_Champions_League#Group_stage" title="2016–17 UEFA Champions League">Champions League group stage</a></td>
    </tr>
  </tbody>
</table> --}}

resources/views/site/partials/_fun-food-fact-card.blade.php
@php
// dd($product, $data);
@endphp

<div class="card">
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="is-48x48">
            <span class="icon is-large is-size-2"><i class="{{App\Repositories\RankingRepository::getIconForGroup($product)}}"></i></span>
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4">{{$product}}</p>
      </div>
    </div>

    <div class="content">
      @foreach($data as $type => $text)
          <p>{!!$text['description']!!}</p>
      @endforeach
    </div>
  </div>
</div>

resources/views/site/partials/_ranking-table.blade.php
<table id="{{ $tab['name'] }}" class="table is-narrow ranking-table" @if(!$loop->first)style="display: none;"@endif>
    <thead>
        <tr>
            <th><abbr title="Posición">#</abbr></th>
            <th>Restaurante</th>
            <th>Precio medio</th>
            <th>Producto/Plato</th>
            <th>Precio</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th><abbr title="Posición">Pos</abbr></th>
            <th>Restaurante</th>
            <th>Precio medio</th>
            <th>Producto/Plato</th>
            <th>Precio</th>
        </tr>
    </tfoot>
    <tbody>
    @foreach($rankings[$tab['name']] as $category => $restaurants)
        @foreach($restaurants as $position => $restaurant)
        <tr class="restaurant-header">
            <th>@if($category=='cheap'){{ ($position + 1) }}@else {{$position}} @endif</th>
            <th title="{{$restaurant->area->name}}">{{ $restaurant->name }} @if(is_null($city)) ({{$restaurant->city->name}}) @endif</th>
            <td>{{ $restaurant->avg_price }}</td>
            <td colspan=2></td>
        </tr>
            @foreach($restaurant->category_dishes as $dish)
        <tr class="dish-row">
            <td colspan="3"></td>
            <td>{{ $dish->name }} @if($dish->description) <small> {{'(' . $dish->description . ')' }}</small>@endif </td>
            <td>{{ $dish->readable_price }}</td>
        </tr>
            @endforeach
        @endforeach
        @if(!$loop->last)
        <tr> <td colspan="6"></td> </tr>
        <tr class="has-text-centered">
            <td colspan="6" style=" text-align:center; ">...</td>
        </tr>
        <tr> <td colspan="6"></td> </tr>
        @endif
    @endforeach
    </tbody>
</table>

resources/views/site/partials/_rankings-tabs.blade.php
<div id="ranking-tabs" class="tabs is-large is-centered is-boxed tabs">
    <ul>
        @foreach($tabs as $tab)
        <li class="@if($loop->first) is-active @endif">
            <a>
            @if(isset($tab['icon']))
                @if (preg_match('/pe-is-f.*/', $tab['icon']))
                    <span class="icon"><i class="{{$tab['icon']}}"></i></span>
                @else
                    <span class="icon"><i class="fa {{$tab['icon']}}"></i></span>
                @endif
            @endif
                <span>{{ $tab['name'] }}</span>
            </a>
        </li>
        @endforeach
    </ul>
</div>